### ISSUE TITLE
注册中心选none直接填host端口会报错

### ISSUE THREAD

**Issue by Younsion** [thubbo/jmeter-plugins-for-apache-dubbo#100]
![image](https://user-images.githubusercontent.com/26084893/69957629-fd97e500-153d-11ea-90e9-fb0391ea028a.png)

**Comment by Younsion** [comment]
我看到代码注释掉了。。。executeTelnet也只有抛异常，请问为什么不支持直连了呢...

**Comment by ningyu1** [comment]
@Younsion 这个错误是点击GetProviderList按钮时提示，获取接口清单只能通过注册中心获取，直连不需要获取接口清单，直连模式的话直接运行sample就可以了

**Comment by Younsion** [comment]
好的，非常感谢
