### ISSUE TITLE
dubbo rpc context

### ISSUE THREAD

**Issue by cheongwen** [thubbo/jmeter-plugins-for-apache-dubbo#101]
调用dubbo服务时，服务端处理逻辑需要获取RpcContext中内容，使用插件时需要如何设置。

目前增加beanshell预处理，服务端不能获取到，请问要如何设置，才能使服务能够正常获取context？
```java
import com.alibaba.dubbo.rpc.RpcContext;

RpcContext.getContext().setAttachment("userId", "xxx");
RpcContext.getContext().setAttachment("userNameCN", "xx");
```

**Comment by ningyu1** [comment]
@cheongwen 
你说的是在jmeter中设置隐士参数给RPC服务端使用。
插件版本[2.7.3](https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/releases/tag/2.7.3)以上版本支持设置隐士参数，具体的用法在方法参数表格的头上有一个切换Attachment表格，这里是设置隐士参数的

**Comment by ningyu1** [comment]
![image](https://user-images.githubusercontent.com/3387548/70691807-efdc1f80-1cf4-11ea-88b0-eaa85e811c38.png)
