### ISSUE TITLE
2.7.4不手动调用get provider list获取服务接口，就没办法连上zk？

### ISSUE THREAD

**Issue by 53066191** [thubbo/jmeter-plugins-for-apache-dubbo#102]
![image](https://user-images.githubusercontent.com/10364655/71944528-0182eb00-31ff-11ea-861e-16ae13338f5e.png)
，手动调用get provider list接口后就能正常连接了
![image](https://user-images.githubusercontent.com/10364655/71944985-773b8680-3200-11ea-95c4-b824e655bf87.png)

**Comment by ningyu1** [comment]
@53066191 
2.7.x之后如果不使用配置中心的话确实有这个问题，可以看这个[issue](https://github.com/apache/dubbo/issues/5276)，问题修复的[PR](https://github.com/apache/dubbo/pull/5518/files)
这个修复还没有发布，最新的Dubbo released版本[2.7.5](https://github.com/apache/dubbo/releases/tag/dubbo-2.7.5)

**Comment by woytu** [comment]
https://github.com/apache/dubbo-spring-boot-project/issues/657#issuecomment-572542407

**Comment by TestUser323** [comment]
我用的是jmeter-plugins-dubbo-2.7.7-jar-with-dependencies.jar版本 点击get provider list按钮也是连接不上提示的错误是这个 zookeeper not connected（地址没有问题 我用telnet测试是可以连通的）config Center 和 Registry Center 两个选项都填写了
![问题](https://user-images.githubusercontent.com/39182299/85196561-912fd800-b30d-11ea-9957-99165f5bd7fb.png)
