### ISSUE TITLE
get provider list的时候连接不上zk，我修改过host文件，不知道这里为什么有的是本地ip连接zk，有的是域名连接zk?

### ISSUE THREAD

**Issue by zhangpan11** [thubbo/jmeter-plugins-for-apache-dubbo#103]
![image](https://user-images.githubusercontent.com/42986249/76060319-f5779780-5fbb-11ea-8e6e-ef1d35e940ba.png)
![image](https://user-images.githubusercontent.com/42986249/76060323-f7d9f180-5fbb-11ea-8d70-93e716473310.png)

**Comment by ningyu1** [comment]
@zhangpan11 
你肯定是用域名连接过又修改为ip了，只要jmeter没关闭过，建立的zk连接都在运行
