### ISSUE TITLE
Java请求和2.7.1以下(包括2.7.1)版本测试dubbo接口结果一致，2.7.1以上版本结果快很多，具体对比结果见附件

### ISSUE THREAD

**Issue by chelx0621** [thubbo/jmeter-plugins-for-apache-dubbo#106]
一、	前置条件
1、	负载机和压测服务都在内网
2、	非GUI执行
3、	测试接口：dubbo接口

二、	测试结果对比
1、	以下为使用dubbo插件方式2.7.1版本50线程和100线程聚合报告
50线程：Average:83ms Throughput:588.5/sec
100线程：Average:168ms Throughput:581.8/sec
2、	以下为使用dubbo插件方式2.7.4/2.7.3版本50线程和100线程聚合报告
50线程：Average:7ms Throughput:405.2/sec
100线程：Average:5ms Throughput:399/sec
3、	以下为使用Java请求方式测试dubbo接口50线程和100线程聚合报告
50线程：Average:82ms Throughput:603.1/sec
100线程：Average:163ms Throughput:608.5/sec
三、	测试结论
使用Java请求方式和2.7.1以下版本dubbo插件测试dubbo接口结果接近，2.7.1以上版本插件方式测试dubbo接口有较大偏差

**Comment by ningyu1** [comment]
@chelx0621 
非常感谢提供测试对比数据
插件版本跟dubbo的版本保持一致的，插件的2.7.4使用的是dubbo-2.7.4.1，dubbo-2.7.4.1优化了泛化调用性能，具体可以看：optimize generic invoke. [#4076](https://github.com/apache/dubbo/pull/4076)
