### ISSUE TITLE
你好，插件下载地址不存在

### ISSUE THREAD

**Issue by tanghuazhen1** [thubbo/jmeter-plugins-for-apache-dubbo#107]
你好，这个下载地址不存在  https://github.com/ningyu1/jmeter-plugins-dubbo/tree/master/dist

**Comment by ningyu1** [comment]
@tanghuazhen1 
https://gitee.com/ningyu/dist-jmeter-plugins-for-apache-dubbo

**Comment by tanghuazhen1** [comment]
收到，谢谢！
