### ISSUE TITLE
什么时候支持nacos注册中心

### ISSUE THREAD

**Issue by hanhaiszw** [thubbo/jmeter-plugins-for-apache-dubbo#112]

**Comment by ningyu1** [comment]
@hanhaiszw 插件版本>=v2.7.4支持nacos

**Comment by hanhaiszw** [comment]
多谢大佬

**Comment by gppwin** [comment]
jmeter-plugins-dubbo-2.7.8-jar-with-dependencies 使用这个版本测试dubbo 走nacos注册中心模式还是错误,选择none 直连模式就ok

**Comment by ningyu1** [comment]
@gppwin 什么错误？贴出来看看
