### ISSUE TITLE
v2.7.7 参数自定义类型，paramValue传入Locale对象值 Dubbo转换失败

### ISSUE THREAD

**Issue by xchnshi** [thubbo/jmeter-plugins-for-apache-dubbo#124]
![image](https://user-images.githubusercontent.com/9674075/95718969-c63bae00-0ca1-11eb-9eb4-3b8f28f7b651.png)
![image](https://user-images.githubusercontent.com/9674075/95719047-deabc880-0ca1-11eb-9bdf-269630d54dd5.png)
图1为jmeter dubbo参数设置，
图2为jmeter日志，提示创建Locale对象时init传入参数都为空时会报的NPE
使用的jmeter dubbo plugin版本为2.7.7

**Comment by ningyu1** [comment]
问题修复在如下版本：
|   插件版本  |
|  ----  |
| [Dubbo Jmeter Plugin v2.7.4.1](https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/releases/tag/2.7.4.1)  |
| [Dubbo Jmeter Plugin v2.7.8](https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/releases/tag/2.7.8)  |

### 如何选择版本？

## 场景：如果需要测试的Dubbo Provider存在多版本（新老版本都有）
使用[Dubbo Jmeter Plugin v2.7.4.1](https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/releases/tag/2.7.4.1)
支持调用的dubbo服务端版本：v2.5.x、v.2.6.x、[v2.7.0-v2.7.4.1]


## 场景：如果需要测试的Dubbo Provider版本>=2.7.0
使用[Dubbo Jmeter Plugin v2.7.8](https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/releases/tag/2.7.8)
支持调用的dubbo服务端版本：>=v2.7.0

ps. 别问为什么听话就对了。
