### ISSUE TITLE
dubbo2.7.7连不上zookeeper

### ISSUE THREAD

**Issue by lvruitao** [thubbo/jmeter-plugins-for-apache-dubbo#127]
![4703F57E-4347-49b0-B97E-87EB26119095](https://user-images.githubusercontent.com/45552347/96396157-17dfbd80-11f9-11eb-9ada-288427804d42.png)

公司的dubbo是2.6.8  用1.3.8插件可以连上

**Comment by ningyu1** [comment]
是的，我已经记录了，请移步：#125
dubbo版本向下兼容的问题

**Comment by ningyu1** [comment]
先使用插件2.7.3一下版本，这个问题重复了我关闭了
