### ISSUE TITLE
mvn install 报错了

### ISSUE THREAD

**Issue by bf109f** [thubbo/jmeter-plugins-for-apache-dubbo#128]
jmeter-plugins-for-apache-dubbo/src/main/java/io/github/ningyu/jmeter/plugin/dubbo/gui/DubboCommonPanel.java:[518,70] 不兼容的类型: java.util.Vector<java.util.Vector>无法转换为java.util.Vector<java.util.Vector<java.lang.String>>

jmeter-plugins-for-apache-dubbo/src/main/java/io/github/ningyu/jmeter/plugin/dubbo/gui/DubboCommonPanel.java:[519,84] 不兼容的类型: java.util.Vector<java.util.Vector>无法转换为java.util.Vector<java.util.Vector<java.lang.String>>

**Comment by zhanggaoqiangcxy** [comment]
java version "12.0.1" 2019-04-16

**Comment by ningyu1** [comment]
@zhanggaoqiangcxy jdk版本太高了，换成jdk8
