### ISSUE TITLE
【版本2.7.7】 版本设置的参数值进行修改后，请求的还是旧值；显示看板有误，只有在请求错误时才显示

### ISSUE THREAD

**Issue by erlou2** [thubbo/jmeter-plugins-for-apache-dubbo#133]
【操作步骤】

存在原始值，修改后再次请求，

【实际结果】

数据请求的还是原始值，不是修改值

![image](https://user-images.githubusercontent.com/32331278/100825064-37256800-3492-11eb-8302-31469929d83f.png)

![image](https://user-images.githubusercontent.com/32331278/100825105-486e7480-3492-11eb-88ee-256f5252b623.png)

【预期结果】

请求实际值和显示值一致

**Comment by ningyu1** [comment]
@erlou2 插件2.7.7对应的dubbo版本v2.7.7
这个问题是dubbo2.7.7的bug，dubbo2.7.8已经修复，建议使用[Dubbo Jmeter Plugin 2.7.8](https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/releases/tag/2.7.8)

**Comment by erlou2** [comment]
好勒 谢谢大佬

**Comment by ningyu1** [comment]
最新修复的稳定版本如下：
|   插件版本  |
|  ----  |
| [Dubbo Jmeter Plugin v2.7.4.1](https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/releases/tag/2.7.4.1)  |
| [Dubbo Jmeter Plugin v2.7.8](https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/releases/tag/2.7.8)  |

### 如何选择版本？

## 场景：如果需要测试的Dubbo Provider存在多版本（新老版本都有）
使用[Dubbo Jmeter Plugin v2.7.4.1](https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/releases/tag/2.7.4.1)
支持调用的dubbo服务端版本：v2.5.x、v.2.6.x、[v2.7.0-v2.7.4.1]


## 场景：如果需要测试的Dubbo Provider版本>=2.7.0
使用[Dubbo Jmeter Plugin v2.7.8](https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/releases/tag/2.7.8)
支持调用的dubbo服务端版本：>=v2.7.0

**Comment by erlou2** [comment]
好勒 十分感谢
