### ISSUE TITLE
[Version 2.7.7]Can't analysis response,always display null

### ISSUE THREAD

**Issue by fattyhan** [thubbo/jmeter-plugins-for-apache-dubbo#134]
1、Run the dubbo test case,the response body always show null,but i run the unit test in IDEA with same parameters get the correct response.
2、The response entity already implements Serializable
3、This issues only occur in response which includ extends relations.

**Comment by ningyu1** [comment]
@fattyhan 
接口的响应对象是个什么结构?麻烦发一下。
有没有观察jmeter console log是否有错误？如果有错误也麻烦贴一下

**Comment by fattyhan** [comment]
@ningyu1 
1、响应对象的结构class ResponseVo extends AbstractResponseVo implements Serializable
      父类
    private String resultCode;
    private String message;
     子类
   Map<String, Object> resultData;
2、jmeter没有异常

**Comment by fattyhan** [comment]
> @fattyhan
> 接口的响应对象是个什么结构?麻烦发一下。
> 有没有观察jmeter console log是否有错误？如果有错误也麻烦贴一下

我把api放到类库里解决了，这是个使用不熟练问题请忽略
