### ISSUE TITLE
空参数在各版本表现不一致

### ISSUE THREAD

**Issue by ccor** [thubbo/jmeter-plugins-for-apache-dubbo#141]
查看结果树发现，对空参数（null）的打印都是"paramValue":"null"，在1.3.x上服务端能收到null，而在2.7.4.1则无法收到。

**Comment by ningyu1** [comment]
![image](https://user-images.githubusercontent.com/3387548/106105166-80d2bc00-617e-11eb-828b-1054ad461bf2.png)
![image](https://user-images.githubusercontent.com/3387548/106105136-73b5cd00-617e-11eb-9761-68e8b9cf9ad0.png)
@ccor 
这个就是插件2.7.41的测试截图
