### ISSUE TITLE
配置中心错填后无法清除导致必须删除取样器并重新创建取样器

### ISSUE THREAD

**Issue by rocketk** [thubbo/jmeter-plugins-for-apache-dubbo#142]
在取样器 Dubbo Sample 的配置界面中的 Config Center / Protocol 下来选择框中如果选择了任意一项，则此项无法被清除，在后面的执行测试计划时，会由于我没有正确填写 Config Center 的 Address 项而发生报错，报错信息：

> Response code:MISS_ADDRESS
Response message:Address is empty!

此Bug的关键不是为何会报错，而是在 Dubbo Sample / Config Center / Protocol 下拉选择框中，应当增加一个“无”选项。

我所使用的版本是 `jmeter-plugins-dubbo-2.7.8-jar-with-dependencies.jar`

**Comment by ningyu1** [comment]
@rocketk 这些配置在容器启动的时候初始化一次会被缓存起来，是为了提高效率
