### ISSUE TITLE
内网压测dubbo  方法什么都没干 就返回了个字符串，测出来tps只有800？？？

### ISSUE THREAD

**Issue by ivanmissu** [thubbo/jmeter-plugins-for-apache-dubbo#146]
![image](https://user-images.githubusercontent.com/8721615/119638507-4f76ae00-be49-11eb-9e7c-3435a9729b0b.png)
如图 内网压测dubbo  方法什么都没干 就返回了个字符串，测出来tps只有800？  这正常吗

**Comment by ningyu1** [comment]
那你看一下服务端的connections配置的是多少？然后试算一下看合不合理

**Comment by ivanmissu** [comment]
> 那你看一下服务端的connections配置的是多少？然后试算一下看合不合理

服务提供没有设置这个值， jmeter插件的connections配置的100

**Comment by ivanmissu** [comment]
> 那你看一下服务端的connections配置的是多少？然后试算一下看合不合理

服务提供没有设置这个值， jmeter插件的connections配置的100

**Comment by ivanmissu** [comment]
服务提供没有设置这个值， jmeter插件的connections配置的100

**Comment by ivanmissu** [comment]
@ningyu1 你好,能帮我看一下吗  急~~

**Comment by ivanmissu** [comment]
![image](https://user-images.githubusercontent.com/8721615/120627096-e836aa80-c495-11eb-9e9f-0a229ed920b8.png)
@ningyu1 是这块代码会影响我并发请求速度吗

**Comment by ningyu1** [comment]
@ivanmissu 不会的，下面已经对大对象做了缓存

https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/blob/2dfcd19f0278acfb5e302f2e2a35a2701ac343e2/src/main/java/io/github/ningyu/jmeter/plugin/dubbo/sample/DubboSample.java#L272

**Comment by ivanmissu** [comment]
@ningyu1 找不到问题了  我在本地起了一个单机dubbo服务，也是才能达到900tps ，  也太奇怪了。 我这边使用的版本是2.7.3  改了2.7.4.1也是这个情况 。  你那边测试单机tps可以达到多少

**Comment by ivanmissu** [comment]
@ningyu1 找到了  我之前用2.7.3只能到900   我换了2.7.8 可以达到20000    有没有兼容问题  alibaba dubbo 2.6.7

**Comment by ningyu1** [comment]
@ivanmissu releases里面有兼容的说明：https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/releases
