### ISSUE TITLE
SamplerResult 无法获取Dubbo ResponseData

### ISSUE THREAD

**Issue by Leowuqunqun** [thubbo/jmeter-plugins-for-apache-dubbo#147]
@Override
    public SampleResult sample(Entry entry) {
        SampleResult res = new SampleResult();
        res.setSampleLabel(getName());
        //构造请求数据
        res.setSamplerData(getSampleData());
        //调用dubbo
        res.setResponseData(JsonUtils.toJson(callDubbo(res)), StandardCharsets.UTF_8.name());
        //构造响应数据
        res.setDataType(SampleResult.TEXT);
        return res;
    }
我看到这里是把返回数据塞到responsedata
 但实际上我并没有拿到他  request body  我都可以拿到 唯独他不可以 
jmeter版本 5.3.0  dubbo 2.7.4   jmeter- dubbo插件版本 2.7.7

**Comment by ningyu1** [comment]
@Leowuqunqun 查询结果树，或者response抽样器都可以拿到data，
可以说一下你是用什么方式拿它吗？

**Comment by Leowuqunqun** [comment]
@ningyu1 
我自己定义了一个类继承org.apache.jmeter.reporters.ResultCollector 
重写 sampleOccurred(SampleEvent e) 方法
如果按照你的方式来说的话我要如何去做，我现在的问题是只有response 无法获取

**Comment by ningyu1** [comment]
@Leowuqunqun 这个就需要去看看jmeter api描述了，
为什么要自己处理response？
可以使用JMeterPlugins-Extras 来增强报告显示

**Comment by Leowuqunqun** [comment]
@ningyu1 我当前基于Jmeter Api 在实现 压测平台，所以会涉及到获取response 做结果的显示和汇总
