### ISSUE TITLE
生产执行dubbo采样器  Exception 急 本地环境是好的

### ISSUE THREAD

**Issue by Leowuqunqun** [thubbo/jmeter-plugins-for-apache-dubbo#148]
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.VerifyError: Bad type on operand stack

Exception Details:
  Location:
    io/github/ningyu/jmeter/plugin/dubbo/sample/DubboSample.callDubbo(Lorg/apache/jmeter/samplers/SampleResult;)Ljava/lang/Object; @1125: invokevirtual
  Reason:
    Type 'org/apache/dubbo/config/ReferenceConfig' (current frame, stack[1]) is not assignable to 'org/apache/dubbo/config/ReferenceConfigBase'
  Current Frame:
    bci: @1125
    flags: { }
    locals: { 'io/github/ningyu/jmeter/plugin/dubbo/sample/DubboSample', 'org/apache/jmeter/samplers/SampleResult', 'org/apache/dubbo/config/ReferenceConfig', 'java/lang/String', 'org/apache/dubbo/config/RegistryConfi
g', 'java/lang/String', 'java/lang/String', 'java/lang/String', 'java/lang/Integer', 'java/lang/String', 'java/lang/Integer', 'java/lang/String', 'java/lang/String', 'java/lang/Integer', 'java/lang/String', 'java/lang
/Integer', 'java/lang/String', 'java/lang/String', 'java/lang/String', 'org/apache/dubbo/config/utils/ReferenceConfigCache' }
    stack: { 'org/apache/dubbo/config/utils/ReferenceConfigCache', 'org/apache/dubbo/config/ReferenceConfig' }
  Bytecode:
    0x0000000: bb00 3a59 b700 3b4d 2cb2 003c b600 3d2a
    0x0000010: b800 1f4e 2db8 003e 9900 2d2a 2bb2 003f
    0x0000020: b600 40b2 0008 bb00 1059 b700 1112 41b6
    0x0000030: 0013 b200 3fb6 0042 b600 14b6 000a b200
    0x0000040: 3fb6 0043 b001 3a04 2ab8 0021 1244 1245
    0x0000050: b600 463a 052a b800 1c3a 062a b800 473a
    0x0000060: 0701 3a08 2ab8 0048 b800 3e9a 000c 2ab8
    0x0000070: 0048 b800 493a 08a7 002f 3a09 b200 08bb
    0x0000080: 0010 59b7 0011 1241 b600 13b2 003f b600
    0x0000090: 42b6 0014 b600 0a2a 2bb2 004b b600 40b2
    0x00000a0: 004b b600 43b0 1906 b800 3e9a 000d 124d
    0x00000b0: 1906 b600 4e99 0052 bb00 4f59 b700 503a

**Comment by ningyu1** [comment]
@Leowuqunqun 异常栈呢？

**Comment by Leowuqunqun** [comment]
@ningyu1 - - 已解决 dubbo版本不一致问题
