### ISSUE TITLE
采样器的Attachment Args有什么用

### ISSUE THREAD

**Issue by yingdianjishu** [thubbo/jmeter-plugins-for-apache-dubbo#152]
![image](https://user-images.githubusercontent.com/46807904/139819480-d4913df2-493b-4cc0-89c2-be4d41472b1d.png)

**Comment by ningyu1** [comment]
@yingdianjishu 请参考[隐式参数使用说明](https://dubbo.apache.org/zh/docs/v3.0/references/features/attachment/#m-zhdocsv30referencesfeaturesattachment)
