### ISSUE TITLE
包装类Long传null报错怎么解决

### ISSUE THREAD

**Issue by alphaJk** [thubbo/jmeter-plugins-for-apache-dubbo#157]
# 请问包装类Long传null报错怎么解决
![image](https://user-images.githubusercontent.com/15723356/183385122-9b151cdd-7bcb-4de4-9aa1-2cca2622a655.png)
![image](https://user-images.githubusercontent.com/15723356/183385244-476caf76-256d-419f-94b9-af1b2a64a26a.png)

**Comment by ningyu1** [comment]
@alphaJk 请看这个
https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/wiki/ParameterComparisonTable
