### ISSUE TITLE
支持设置调用方名称吗？目前jmeter去调用dubbo的名称为空

### ISSUE THREAD

**Issue by hqgordon** [thubbo/jmeter-plugins-for-apache-dubbo#158]
支持设置调用方名称吗？目前jemeter去调用dubbo的名称为空

**Comment by ningyu1** [comment]
支持

**Comment by hqgordon** [comment]
> 支持

怎么去设置呢 麻烦求教一下

**Comment by ningyu1** [comment]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/3387548/192460431-79e73544-c0d8-4460-8251-785332c8d501.png">
Method里面输入方法名
Interface里面输入接口名

**Comment by ningyu1** [comment]
> 怎么去设置呢 麻烦求教一下

调用方名字是固定的：DubboSample
