### ISSUE TITLE
请问参数是String类型怎么传参，还有版本号和group都没有的接口怎么设置

### ISSUE THREAD

**Issue by lvruitao** [thubbo/jmeter-plugins-for-apache-dubbo#40]

**Comment by ningyu1** [comment]
@lvruitao version和group如果接口没有传入空即可，参数传递参考[FAQ](https://github.com/dubbo/jmeter-plugins-dubbo/wiki/FAQ),有复杂参数以及泛型支持

**Comment by ningyu1** [comment]
你也可以在issue中搜索，问这个问题的人还是蛮多的，在以前的issue能找到答案
