### ISSUE TITLE
使用jmeter配置扩展做dubbo全局配置模块

### ISSUE THREAD

**Issue by qianyewhy** [thubbo/jmeter-plugins-for-apache-dubbo#43]
大佬，我用这个插件好久了，从还需要代码jar包，到可以通过dubbo泛化调用直接调用dubbo接口。虽然我下载了，但还没看过插件源码，惭愧。想提优化需求，小小建议。
第一个就是，jmeter有个元件，http默认请求，想问下，您有时间的话，能封装个dubbo默认请求就好了，不然每次需要改IP都得手动一个个改很费时间。
第二个，不知道是不是没做转码，现在的dubbo接口返回的中文都是乱码，这个能改善下就好了
大神，小小建议，没有别的意思哈，希望这个插件的功能越来越完善，用的人越来越多，测dubbo接口真的超级方便，膜拜大佬～

**Comment by ningyu1** [comment]
第一个个提议很好的，我也是有考虑把公共的参数设置做一个dubbo的配置单元来进行默认参数的初始化。

第二个请求乱码没遇到过，结果都是UTF-8的编码格式，难道你们的返回不是UTF-8的？

**Comment by sofkyle** [comment]
> 第二个，不知道是不是没做转码，现在的dubbo接口返回的中文都是乱码，这个能改善下就好了

断点调试的时候，发现返回的中文是正常的，
![image](https://user-images.githubusercontent.com/7426860/62388736-aafaec00-b590-11e9-9efe-4c2af1cc87bc.png)

但是在Jmeter中显示时，变成了乱码，猜想可能是Jmeter本身的设置问题。
在${JMETER_HOME}/bin/jmeter.properties中增加如下配置：
**sampleresult.default.encoding=UTF-8**
问题得到解决：
![image](https://user-images.githubusercontent.com/7426860/62389000-4a1fe380-b591-11e9-9856-96b63d10fde6.png)

@qianyewhy 不知道能不能帮助你。

**Comment by ningyu1** [comment]
https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/wiki/FAQ#%E8%BF%90%E8%A1%8Cjmeter%E6%97%B6%E5%93%8D%E5%BA%94%E6%95%B0%E6%8D%AE%E4%B8%AD%E6%96%87%E4%B9%B1%E7%A0%81%E9%97%AE%E9%A2%98

**Comment by kelystor** [comment]
@qianyewhy 可以试下这个插件：[https://github.com/kelystor/yajad-jmeter-dubbo-plugin](https://github.com/kelystor/yajad-jmeter-dubbo-plugin)，一样是JMeter测dubbo的插件，实现了“默认请求”配置元件，输出已经自动设置编码，不会有中文乱码

**Comment by ningyu1** [comment]
@kelystor 可以提交特性pr到这个仓库共同建设

**Comment by ningyu1** [comment]
[2.7.3 Pre-release Download](https://gitee.com/ningyu/dist-jmeter-plugins-for-apache-dubbo)

**Comment by kelystor** [comment]
@ningyu1 看你的新版本已经改进了很多了，也不需要什么PR了。我写那个插件，只是因为公司使用的dubbox和你这个不够契合，现在自己的插件已经能满足公司使用了，没有什么特别的问题和需要，我也不会把精力放在JMeter插件上，要去做别的东西了。你继续加油吧，造福各位JMeter Dubbo同仁。
