### ISSUE TITLE
dubbo调用长连接未回收

### ISSUE THREAD

**Issue by gosuTopData1** [thubbo/jmeter-plugins-for-apache-dubbo#55]
这个有什么解决方案么？
把副武器的文件打开数占满了.....

**Comment by ningyu1** [comment]
你说的是接口服务端的还是客户端？

**Comment by gosuTopData1** [comment]
服务端的

**Comment by ningyu1** [comment]
dubbo有连接复用的，如果没有配置默认是100，除非你们服务端有配置connection数量，而且服务器的打开文件数也是可以调整的通过ulimit -n查看，根据你们的场景来调整
