### ISSUE TITLE
支持从Nacos注册中心中获取Services

### ISSUE THREAD

**Issue by exceedzhang** [thubbo/jmeter-plugins-for-apache-dubbo#57]
是否支持从Nacos注册中心中获取Services？如何是否操作？

**Comment by ningyu1** [comment]
@exceedzhang 目前还没有支持，先记录一下后续支持

**Comment by ningyu1** [comment]
#98

**Comment by ningyu1** [comment]
https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/releases/tag/2.7.4
