### ISSUE TITLE
dubbo接口参数类型是List<Enum>，怎么传参？

### ISSUE THREAD

**Issue by chzhiyi** [thubbo/jmeter-plugins-for-apache-dubbo#77]
**dubbo接口**如下：public Map<String, Map<String, String>> getInfoList(String month, List<String> artisanIds, List`<InfoEnum>` itemNames)
**InfoEnum代码**如下：
public enum InfoEnum {
    EFF_USER_CNT("user_cnt", "成交用户", "人", "Int"),
    private String key;
    private String name;
    private String unit;
    private String type;
    private InfoEnum(String key, String name, String unit, String type) {
        this.key = key;
        this.name = name;
        this.unit = unit;
        this.type = type;
    }
    public String getName() {
        return this.name;
    }
    public String getKey() {
        return this.key;
    }
    public String getUnit() {
        return this.unit;
    }
    public String getType() {
        return this.type;
    }
    public static InfoEnum getByKey(String key) {
        for (InfoEnum type : InfoEnum.values()) {
            if (type.getKey().equals(key)) {
                return type;
            }
        }
        return null;
    }
}
** **
public enum InfoEnum {
    EFF_USER_CNT("eff_user_cnt", "成交用户", "人", "Int"),
    EFF_NEW_USER_CNT("eff_new_user_cnt", "新客成交用户", "人", "Int"),
    EFF_OLD_USER_CNT("eff_old_user_cnt", "老客成交用户", "个", "Int"),
    private String key;
    private String name;
    private String unit;
    private String type;
    private InfoEnum(String key, String name, String unit, String type) {
        this.key = key;
        this.name = name;
        this.unit = unit;
        this.type = type;
    }
    public String getName() {
        return this.name;
    }
    public String getKey() {
        return this.key;
    }
    public String getUnit() {
        return this.unit;
    }
    public String getType() {
        return this.type;
    }
    public static InfoEnum getByKey(String key) {
        for (InfoEnum type : InfoEnum.values()) {
            if (type.getKey().equals(key)) {
                return type;
            }
        }
        return null;
    }
}

**jmeter中传参如下，报错java.lang.NullPointerException**
Method Args: [{"paramType":"String","paramValue":"201906"}, {"paramType":"String","paramValue":"180606t"}, {"paramType":"java.util.List","paramValue":"[{\"key\":\"eff_order_cnt\",\"name\",\"订单量\",\"unit\":\"个\",\"type\":\"Int\"}]"}]

**Comment by ningyu1** [comment]
@chzhiyi 
paramType：java.util.List
paramValue：["EFF_USER_CNT","EFF_NEW_USER_CNT","EFF_OLD_USER_CNT",.........]
