### ISSUE TITLE
时间格式被转化为"Jun 25, 2019 6:00:00 PM" ，并不是我想要的“yyyy-MM-dd”

### ISSUE THREAD

**Issue by erlou2** [thubbo/jmeter-plugins-for-apache-dubbo#78]

**Comment by erlou2** [comment]
目前的数据库存储值2019-06-25 09:42:12，
但是在dubbo 请求后显示的时间格式的值"Jun 25, 2019 10:00:00 PM"，我改如何处理此类格式的转化为yyyy-MM-dd hh:mm:ss格式的

**Comment by erlou2** [comment]
> _No description provided._
目前接口返回格式 ：Jun 25, 2019 10:00:00 PM
数据格式：2019-06-25 10:00:00
后台需要格式：2019-06-25 10:00:00
然后导致后台程序解析失败：
目前看得好像用的gson,不知道该怎么处理

**Comment by ningyu1** [comment]
@erlou2 插件版本提供一下

**Comment by erlou2** [comment]
jmeter-plugins-dubbo-1.3.8-jar-with-dependencies @ningyu1

**Comment by kelystor** [comment]
可以试下这个插件：[https://github.com/kelystor/yajad-jmeter-dubbo-plugin](https://github.com/kelystor/yajad-jmeter-dubbo-plugin)，一样是JMeter测dubbo的插件，日期输出做了美化格式化处理

**Comment by erlou2** [comment]
> 可以试下这个插件：https://github.com/kelystor/yajad-jmeter-dubbo-plugin，一样是JMeter测dubbo的插件，日期输出做了美化格式化处理

十分感谢您的帮助，但是看了下 大致的简介并没有看到我急需解决的内容。十分感谢

**Comment by ningyu1** [comment]
[2.7.3 Pre-release Changlog](https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/releases/tag/2.7.3)
[2.7.3 Pre-release Download](https://gitee.com/ningyu/dist-jmeter-plugins-for-apache-dubbo)
