### ISSUE TITLE
dubbo2.7.3 is comming up, is there any plan to support 2.7.3

### ISSUE THREAD

**Issue by dhchao11** [thubbo/jmeter-plugins-for-apache-dubbo#79]
dubbo2.7.3 is comming up, is there any plan to support 2.7.3

**Comment by ningyu1** [comment]
会支持的 @dhchao11

**Comment by kelystor** [comment]
可以试下这个插件：[https://github.com/kelystor/yajad-jmeter-dubbo-plugin](https://github.com/kelystor/yajad-jmeter-dubbo-plugin)，一样是JMeter测dubbo的插件，可以支持各种dubbo版本

**Comment by ningyu1** [comment]
@dhchao11 
https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/releases/tag/2.7.1
