### ISSUE TITLE
插件在实际压测时性能结果低

### ISSUE THREAD

**Issue by pegasusair** [thubbo/jmeter-plugins-for-apache-dubbo#81]
实际压测结果发现，使用您这个插件对比用“建立类继承AbstractJavaSamplerClient类，重写runTest方法”的方案，后者性能结果更好，后者的性能结果高了约50%，测试条件是相同环境同一个接口，相同并发数下查看Throughput、99%Line，请作者关注并优化，谢谢 。

**Comment by ningyu1** [comment]
@pegasusair 感谢提问，sample在记录时间的时候是统计了一些不应该算入的时间

**Comment by pegasusair** [comment]
@ningyu1 感谢回复，目前有什么优化方案吗？或者我通过什么方案可以规避这个问题？求解。您这个插件对于验证dubbo服务的接口测试是非常方便的，所以我很想使用这个插件做性能测试。

**Comment by ningyu1** [comment]
@pegasusair 目前规避不了，我最近会更新支持dubbo2.7.3，顺便解决这个bug

**Comment by pegasusair** [comment]
@ningyu1 非常感谢，期盼中！

**Comment by ningyu1** [comment]
[2.7.3 Pre-release Download](https://gitee.com/ningyu/dist-jmeter-plugins-for-apache-dubbo)

**Comment by pegasusair** [comment]
@ningyu1 
使用2.7.1压测，相同接口200并发下的Throughput是428；
使用2.7.3压测，相同接口200并发下的Throughput是488；
使用重写runTest方法压测，相同接口200并发下的Throughput是1500。

**Comment by ningyu1** [comment]
@pegasusair 
相差这么多？
runTest中你是怎么调用的？

**Comment by pegasusair** [comment]
@ningyu1 public SampleResult runTest(JavaSamplerContext arg0) {
		System.out.println("---------------------------runtest-----------------------------");
		SampleResult results = new SampleResult();
		results.sampleStart();// jmeter 开始统计响应时间标记
		try{
			
			PreDefAccBalRequest request=new PreDefAccBalRequest();
			RequestHeader reqHeader=new RequestHeader();
			reqHeader.setReqDate("20190819");
			reqHeader.setReqTime("110011");
			reqHeader.setSysCode("test");
			request.setReqHeader(reqHeader);

			request.setAccType(arg0.getParameter("AccType"));
			request.setUserNo(arg0.getParameter("UserNo"));
			
			SearchResponse<PreDefAccBalItem> resp=null;
			resp=balService.preDefAccBalSearch(request);
			System.out.println("---------------------"+resp.toString());
			
			results.setRequestHeaders(arg0.getParameter("AccType"));
			results.setRequestHeaders(arg0.getParameter("UserNo"));
			results.setResponseData(JSONObject.toJSONString(resp));
			
			if(resp.getResHeader().getRespCode().equals("0000")){
				results.setSuccessful(true);
			}else{
				results.setSuccessful(false);
			}
		}catch(Exception e){
			results.setSuccessful(false);
		}finally {
			results.sampleEnd();// jmeter 结束统计响应时间标记
		}

		return results;

	}

**Comment by ningyu1** [comment]
@pegasusair runTest中是直接调用，不是泛化调用方式，有空测试一下换成泛化的写法来调用看看性能相差多少？ 有可能是泛化调用性能不高

**Comment by pegasusair** [comment]
@ningyu1 泛化调用还不会。。您能给个demo吗？

**Comment by ningyu1** [comment]
@pegasusair 
照着官方的示例写：http://dubbo.apache.org/zh-cn/blog/dubbo-generic-invoke.html
```
ApplicationConfig application = new ApplicationConfig()ApplicationConfig application = new ApplicationConfig();
application.setName("api-generic-consumer");

RegistryConfig registry = new RegistryConfig();
registry.setAddress("zookeeper://127.0.0.1:2181");

application.setRegistry(registry);

ReferenceConfig<GenericService> reference = new ReferenceConfig<GenericService>();
// 弱类型接口名
reference.setInterface("com.alibaba.dubbo.samples.generic.api.IUserService");
// 声明为泛化接口
reference.setGeneric(true);

reference.setApplication(application);

// 用com.alibaba.dubbo.rpc.service.GenericService可以替代所有接口引用
GenericService genericService = reference.get();

String name = (String) genericService.$invoke("delete", new String[]{int.class.getName()}, new Object[]{1});
System.out.println(name);
```

**Comment by CodingSinger** [comment]
pay close attention to this issue

**Comment by CodingSinger** [comment]
@pegasusair  最后的结果呢
