### ISSUE TITLE
服务提供者使用java序列化方式，而不是使用dubbo默认的序列化方式，响应时报错

### ISSUE THREAD

**Issue by kedongyu** [thubbo/jmeter-plugins-for-apache-dubbo#84]
"detailMessage": "java.io.StreamCorruptedException: invalid stream header: 77020101\r\n
		java.io.StreamCorruptedException: invalid stream header: 77020101\r\n\tat 
		java.io.ObjectInputStream.readStreamHeader(Unknown Source)\r\n\tat 
		java.io.ObjectInputStream.<init>(Unknown Source)\r\n\tat 
		org.apache.dubbo.common.serialize.java.JavaObjectInput.<init>(JavaObjectInput.java:33)\r\n\tat 
		org.apache.dubbo.common.serialize.java.JavaSerialization.deserialize(JavaSerialization.java:54)\r\n\tat 
		org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:76)\r\n\tat 
		org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:112)\r\n\tat 
		org.apache.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:90)\r\n\tat 
		org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:122)\r\n\tat 
		org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:82)\r\n\tat 
		org.apache.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:46)\r\n\tat 
		org.apache.dubbo.remoting.transport.netty4.NettyCodecAdapter$InternalDecoder.decode(NettyCodecAdapter.java:90)\r\n\tat 
		io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)\r\n\tat 
		io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)\r\n\tat 
		io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)\r\n\tat 
		io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)\r\n\tat 
		io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)\r\n\tat 
		io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)\r\n\tat 
		io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)\r\n\tat 
		io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)\r\n\tat 
		io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)\r\n\tat 
		io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)\r\n\tat 
		io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\r\n\tat 
		io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)\r\n\tat 
		io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)\r\n\tat
		io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)\r\n\tat 
		io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)\r\n\tat 
		io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)\r\n\tat
		io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\r\n\tat

**Comment by kedongyu** [comment]
服务提供者配置文件application.properties部分配置信息：

#注册中心地址
spring.dubbo.registry.address = zookeeper://127.0.0.1:2181
#接口组名称
spring.dubbo.protocol.name=dubbo
#序列化接口
spring.dubbo.protocol.serialization=java
#序列化编码
spring.dubbo.protocol.charset=UTF-8

**Comment by kedongyu** [comment]
搞定，java版本要统一，改用java jdk1.7+jmeter 3.0 + 插件1.3.x版本，服务提供者编译时使用jdk1.7

**Comment by kedongyu** [comment]
发现，java jdk1.8+jmeter5+插件1.3.8也是可以的，主要问题还是在插件版本上，

**Comment by ningyu1** [comment]
@kedongyu 插件1.3.x是jdk7编译的所以使用jdk8运行是没有问题，2.7.x的版本是jdk8编译的所以只能使用jdk8运行
具体可以看[readme](https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/blob/master/README.md)上支持的版本说明
