### ISSUE TITLE
目前是否支持dubbo rpc隐式参数传递呢，如何支持

### ISSUE THREAD

**Issue by pengfeiLuky** [thubbo/jmeter-plugins-for-apache-dubbo#85]
是否支持dubbo rpc隐式参数传递呢？如何支持

**Comment by ningyu1** [comment]
@pengfeiLuky BeanShellScript内直接写Java Code 就可以支持

**Comment by pengfeiLuky** [comment]
是下面这样写吗？还是鉴权不通过，确定参数是对的。具体写大神法求指导
import com.alibaba.dubbo.rpc.RpcContext;
RpcContext.getContext().setAttachment("appName", "xxx");
RpcContext.getContext().setAttachment("appAuthKey", "xxx");

**Comment by pengfeiLuky** [comment]
@ningyu1 您好 能给个样例吗？急用，感谢！！

**Comment by ningyu1** [comment]
@pengfeiLuky jmeter中写要用org.apache.dubbo 因为插件的2.7.x已经升级到dubbo2.7.x，包名是不对的
如果你用的是1.3.x的插件这样写法是可以的

**Comment by ningyu1** [comment]
@pengfeiLuky 我刚才测试了一下BeanShellScript不能满足隐士传参的效果
目前插件还没有把隐士传参扩展出来

**Comment by ningyu1** [comment]
@pengfeiLuky 
https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/releases/tag/2.7.3
