### ISSUE TITLE
入参有Date型如何传递？使用时间戳，或者按对应日期格式的字符参数均无法通过校验。

### ISSUE THREAD

**Issue by maomaofeitui** [thubbo/jmeter-plugins-for-apache-dubbo#86]
入参有Date型如何传递？使用时间戳，或者按对应日期格式的字符参数均无法通过校验。
报错如下：
Unparseable date: \"\"\njava.lang.IllegalStateException: Failed to parse date  by format yyyy-MM-dd HH:mm:ss, cause: Unparseable date: \"\"\n\tat com.alibaba.dubbo.common.utils.CompatibleTypeUtils.compatibleTypeConvert(CompatibleTypeUtils.java:86)\n\tat

**Comment by ningyu1** [comment]
yyyy-MM-dd HH:mm:ss 按照这个格式

**Comment by ningyu1** [comment]
@maomaofeitui 

![image](https://user-images.githubusercontent.com/3387548/64247968-86ed4a80-cf42-11e9-91c0-15f91a0ea9a5.png)

![image](https://user-images.githubusercontent.com/3387548/64247990-9a98b100-cf42-11e9-9726-9fd24fd52526.png)
