### ISSUE TITLE
请问一下可以像http或java请求一样设置默认值吗

### ISSUE THREAD

**Issue by tianxinyueming** [thubbo/jmeter-plugins-for-apache-dubbo#93]
![image](https://user-images.githubusercontent.com/49472119/65829792-a37b6900-e2db-11e9-8e4b-8dca2a0a3fa7.png)

**Comment by sofkyle** [comment]
@tianxinyueming 最新版本中已经加入了Dubbo Config

**Comment by tianxinyueming** [comment]
> @tianxinyueming 最新版本中已经加入了Dubbo Config

多谢

**Comment by ningyu1** [comment]
@tianxinyueming 
[2.7.3版本](https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/releases/tag/2.7.3)

**Comment by tianxinyueming** [comment]
> @tianxinyueming
> [2.7.3版本](https://github.com/thubbo/jmeter-plugins-for-apache-dubbo/releases/tag/2.7.3)

![image](https://user-images.githubusercontent.com/49472119/66386868-6dce3280-e9f5-11e9-97dc-b7cbc6feb714.png)
希望大佬可以在getproviderlist这边加上模糊匹配的功能，测试环境大家zk上注册过多个项目，providerlist里面的接口过多直接在下拉框里找不太好找
类似web上的 <select class="width-90 chosen-select" id="cboInterfaces" data-placeholder="请选择接口">
![image](https://user-images.githubusercontent.com/49472119/66387221-1d0b0980-e9f6-11e9-97ac-9b5bcc92361a.png)



小小建议哈

**Comment by ningyu1** [comment]
@tianxinyueming 输入Service名称回车就是模糊查询，回车后有名字一样的会直接选中
