### ISSUE TITLE
请问如果多个参数为同一类型，怎么填写？

### ISSUE THREAD

**Issue by 1015735512** [thubbo/jmeter-plugins-for-apache-dubbo#96]
例如，接口定义3个参数，id（int），name（string），age（string），这种情况下，在jmeter测试中怎么填写？

**Comment by ningyu1** [comment]
@1015735512 
添加三行参数就可以了，参考：

|paramType|paramValue|
|:-|:-|
|int |1|
|String |name|
|String |age|
